version: '3.8'

services:
  database: 
    image: postgres:alpine
    container_name: database_contele
    environment:
      - POSTGRES_USER=marcelo
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=contele_db
    ports:
      - 5432:5432
    volumes:
      - pgdata:/data/postgres
  
  
    
volumes: 
    pgdata:
      driver: local