version: '3.8'

services:
  database: 
    image: postgres:14.2
    container_name: database_contele
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=contele_db
    volumes:
      - pgdata:/data/postgres
  
  app:
    build: .
    container_name: app_contele
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database
    
volumes: 
    pgdata:
      driver: local