version: '3.9'

services:
  database: 
    image: postgres
    container_name: database_contelle
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=contelle_db
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: contelle
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database
    
volumes: 
    pgdata:
      driver: local